export type {
  EvaluateOpportunityMatrixInput,
  EvaluateOpportunityVariantInput,
  EvaluateOpportunityVariantsInput,
  OpportunityEngineScanResultDto,
  OpportunityEngineVariantResultDto,
  OpportunityExecutionBreakdownDto,
  OpportunityEvaluationDto,
  OpportunityEligibilityDto,
  OpportunityExplainabilityDto,
  OpportunityFunnelMetricsDto,
  OpportunityPairabilityDto,
  OpportunityPairabilityStatus,
  OpportunityPenaltyBreakdownDto,
  OpportunityRankingInputsDto,
  OpportunityRiskReasonDto,
  OpportunityComponentScoresDto,
  OpportunitySourceLegDto,
  OpportunityStrictTradableKeyDto,
  OpportunityStrictTradableMatchDto,
  OpportunityPreScoreGateDto,
  OpportunityValidationDto,
  OpportunityValidationStatus,
} from '../domain/opportunity-engine.contract';
