export type {
  EvaluateOpportunityMatrixInput,
  EvaluateOpportunityVariantInput,
  EvaluateOpportunityVariantsInput,
  OpportunityEngineScanResultDto,
  OpportunityEngineVariantResultDto,
  OpportunityEvaluationDto,
  OpportunityExplainabilityDto,
  OpportunityPairabilityDto,
  OpportunityPairabilityStatus,
  OpportunityPenaltyBreakdownDto,
  OpportunityRankingInputsDto,
  OpportunitySourceLegDto,
  OpportunityValidationDto,
  OpportunityValidationStatus,
} from '../domain/opportunity-engine.contract';
