export const BACKUP_AGGREGATOR_SYNC_QUEUE_NAME =
  'backup-aggregator-sync-batches';
export const BACKUP_AGGREGATOR_SYNC_JOB_NAME =
  BACKUP_AGGREGATOR_SYNC_QUEUE_NAME;
export const BACKUP_AGGREGATOR_SYNC_QUEUE = Symbol(
  'BACKUP_AGGREGATOR_SYNC_QUEUE',
);
export const BACKUP_REFERENCE_PROVIDERS = Symbol('BACKUP_REFERENCE_PROVIDERS');
