export const CSFLOAT_SYNC_LISTINGS_QUEUE_NAME = 'csfloat-sync-listings';
export const CSFLOAT_FETCH_LISTING_DETAIL_QUEUE_NAME =
  'csfloat-fetch-listing-detail';

export const CSFLOAT_SYNC_LISTINGS_JOB_NAME = CSFLOAT_SYNC_LISTINGS_QUEUE_NAME;
export const CSFLOAT_FETCH_LISTING_DETAIL_JOB_NAME =
  CSFLOAT_FETCH_LISTING_DETAIL_QUEUE_NAME;

export const CSFLOAT_SYNC_LISTINGS_QUEUE = Symbol(
  'CSFLOAT_SYNC_LISTINGS_QUEUE',
);
export const CSFLOAT_FETCH_LISTING_DETAIL_QUEUE = Symbol(
  'CSFLOAT_FETCH_LISTING_DETAIL_QUEUE',
);

export const CSFLOAT_LISTINGS_ENDPOINT_NAME = 'csfloat-listings';
export const CSFLOAT_LISTING_DETAIL_ENDPOINT_NAME = 'csfloat-listing-detail';
