export const SKINPORT_SYNC_ITEMS_QUEUE_NAME = 'skinport-sync-items-snapshot';
export const SKINPORT_SYNC_SALES_HISTORY_QUEUE_NAME =
  'skinport-sync-sales-history';
export const SKINPORT_INGEST_SALE_FEED_QUEUE_NAME = 'skinport-ingest-sale-feed';

export const SKINPORT_SYNC_ITEMS_JOB_NAME = SKINPORT_SYNC_ITEMS_QUEUE_NAME;
export const SKINPORT_SYNC_SALES_HISTORY_JOB_NAME =
  SKINPORT_SYNC_SALES_HISTORY_QUEUE_NAME;
export const SKINPORT_INGEST_SALE_FEED_JOB_NAME =
  SKINPORT_INGEST_SALE_FEED_QUEUE_NAME;

export const SKINPORT_SYNC_ITEMS_QUEUE = Symbol('SKINPORT_SYNC_ITEMS_QUEUE');
export const SKINPORT_SYNC_SALES_HISTORY_QUEUE = Symbol(
  'SKINPORT_SYNC_SALES_HISTORY_QUEUE',
);
export const SKINPORT_INGEST_SALE_FEED_QUEUE = Symbol(
  'SKINPORT_INGEST_SALE_FEED_QUEUE',
);
