export const ARCHIVE_RAW_PAYLOAD_QUEUE_NAME = 'archive-raw-payload';
export const NORMALIZE_SOURCE_PAYLOAD_QUEUE_NAME = 'normalize-source-payload';
export const UPDATE_MARKET_STATE_QUEUE_NAME = 'update-market-state';

export const ARCHIVE_RAW_PAYLOAD_JOB_NAME = ARCHIVE_RAW_PAYLOAD_QUEUE_NAME;
export const NORMALIZE_SOURCE_PAYLOAD_JOB_NAME =
  NORMALIZE_SOURCE_PAYLOAD_QUEUE_NAME;
export const UPDATE_MARKET_STATE_JOB_NAME = UPDATE_MARKET_STATE_QUEUE_NAME;

export const ARCHIVE_RAW_PAYLOAD_QUEUE = Symbol('ARCHIVE_RAW_PAYLOAD_QUEUE');
export const NORMALIZE_SOURCE_PAYLOAD_QUEUE = Symbol(
  'NORMALIZE_SOURCE_PAYLOAD_QUEUE',
);
export const UPDATE_MARKET_STATE_QUEUE = Symbol('UPDATE_MARKET_STATE_QUEUE');
